### ISSUE TITLE
Mod breaks mirror functionality

### ISSUE THREAD

**Issue by cmccord-dev** [insteadofnothing/dd-flexible-resize#1]
The mirror functionality is broken when using this mod.  Holding the hotkey (default A) does nothing, and pressing the mirror button in the select tool causes the y scale to be set to 0.1.

My assumption is the sliders are enforcing a minimum positive value and the mirror tool is attempting to set one of the scales to a negative value.

**Comment by insteadofnothing** [comment]
Are you using version 1.2.1? It should be fixed since that update.

**Comment by cmccord-dev** [comment]
Ahh ok, yeah I was on 1.1.0 apparently.  Shame there's no easy way of indicating updates are available.  Thank you!
